device: auto
train:
  - _target_: src.metrics.example.ExampleMetric
    name: TRAIN_Accuracy
    device: ${metrics.device}
    metric: null
    pos_index: 1
inference:
  - _target_: src.metrics.example.ExampleMetric
    name: Accuracy
    device: ${metrics.device}
    metric: null
    pos_index: 1
  - _target_: src.metrics.example.ExampleMetric
    name: F1
    device: ${metrics.device}
    metric: null
    pos_index: 1
  - _target_: src.metrics.example.ExampleMetric
    name: AUROC
    device: ${metrics.device}
    metric: null
    pos_index: 1
  - _target_: src.metrics.example.ExampleMetric
    name: EER
    device: ${metrics.device}
    metric: null
    pos_index: 1
